### ISSUE TITLE
Cannot execute Cova with Configuration sample files and applications

### ISSUE THREAD

**Issue by malinaaa** [secure-software-engineering/COVA#2]
Hello, 

I have just compiled cova and tried to test it with cmd following the example you provided in the main git page of this project. Unfortunately, I face this error and cannot get the analysis result:

malina@malina-OptiPlex-7060:~/Documents/Tools/COVA$ java -jar ./cova/target/cova-0.0.1-SNAPSHOT.jar -android -config cova/src/test/resources/config -p ../Benchmarks/AndroidPlatforms/ -apk constraintBench/androidApps/apks/Callbacks1.apk 
[main] INFO cova.setup.RunFlowDroid - Run FlowDroid...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException
	at cova.setup.RunFlowDroid.run(RunFlowDroid.java:89)
	at cova.runner.AndroidApkAnalyzer.analyzeApk(AndroidApkAnalyzer.java:297)
	at cova.runner.AndroidApkAnalyzer.analyze(AndroidApkAnalyzer.java:231)
	at cova.runner.AndroidApkAnalyzer.main(AndroidApkAnalyzer.java:89)
	at cova.Main.main(Main.java:99)
Caused by: java.lang.ClassNotFoundException: javax.activation.UnsupportedDataTypeException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more

I would be grateful if you can help me with solving it asap.

**Comment by linghuiluo** [comment]
i just tried this in my laptop with java 8 and it works ` java -jar cova-0.0.1-SNAPSHOT.jar -android -config E:\COVA\cova\config -p E:\COVA\cova\src\test\resources\androidPlatforms -apk E:\COVA\constraintBench\androidApps\apks\Callbacks1.apk`
Can you please use the config in under `cova\config` not the one in the `test/resources`? the android platforms i am not sure if you have the right ones, please try to use the one in `cova\src\test\resources\androidPlatforms`.

**Comment by linghuiluo** [comment]
Otherwise you have to debug the problem. The main class is here https://github.com/secure-software-engineering/COVA/blob/master/cova/src/main/java/cova/Main.java

**Comment by malinaaa** [comment]
The problem was due to incorrect version of Java I used. Now by migrating to java version 8, I can successfully run the analysis. 
There is also other problem I have now. When I try to analyze an apk that I have implemented by myself, I see lots of warnings and the final result is no leakage. Whilst, the application leak IMEA to external storage when user clicks a button.  

The link of the application is here:
https://drive.google.com/file/d/1U7QGDf-DgLXdvnObzNepHRtvzIWKSZYE/view?usp=sharing

Can you help me with clarifying the warnings I receive? 

The result of analysis is here:

ava -jar ./cova/target/cova-0.0.1-SNAPSHOT.jar -android -config cova/src/test/resources/config -p ../Benchmarks/AndroidPlatforms/ -apk /media/malina/2312-47F7/Android\ apk/IF_explicit.apk 
[main] INFO cova.setup.RunFlowDroid - Run FlowDroid...
[main] INFO soot.jimple.infoflow.taintWrappers.EasyTaintWrapper - Loaded wrapper entries for 89 classes and 12 exclusions.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Initializing Soot...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Loading dex files...
[main] WARN soot.dexpler.DexFileProvider - Multiple dex files detected, only processing 'classes.dex'. Use '-process-multiple-dex' option to process them all.
[main] INFO soot.jimple.infoflow.android.SetupApplication - ARSC file parsing took 0.002646008 seconds
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Cannot generate constructor for phantom class com.example.malina.if_covert_rec_storage.MainActivity
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Constructor cannot be generated for application class com.example.malina.if_covert_rec_storage.MainActivity
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Constructor cannot be generated for com.example.malina.if_covert_rec_storage.MainActivity
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Could not find a suitable constructor for class com.android.tools.ir.server.InstantRunContentProvider
[main] WARN soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator - Constructor cannot be generated for com.android.tools.ir.server.InstantRunContentProvider
[main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Collecting callbacks in DEFAULT mode...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Callback analysis done.
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] INFO soot.jimple.infoflow.android.SetupApplication - Callback analysis terminated normally
[main] INFO soot.jimple.infoflow.android.SetupApplication - Entry point calculation done.
[main] INFO soot.jimple.infoflow.android.source.AccessPathBasedSourceSinkManager - Created a SourceSinkManager with 46 sources, 122 sinks, and 0 callback methods.
[main] INFO soot.jimple.infoflow.android.SetupApplication - Running data flow analysis on /media/malina/2312-47F7/Android apk/IF_covert_rec.apk with 46 sources and 122 sinks...
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Implicit flow tracking is NOT enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Exceptional flow tracking is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Running with a maximum access path length of 5
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using path-agnostic result collection
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Recursive access path shortening is enabled
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Taint analysis enabled: true
[main] INFO soot.jimple.infoflow.InfoflowConfiguration - Using alias algorithm FlowSensitive
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph construction took 1.72474E-4 seconds
[main] INFO soot.jimple.infoflow.codeOptimization.InterproceduralConstantValuePropagator - Removing side-effect free methods is disabled
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Dead code elimination took 0.007831906 seconds
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Callgraph has 0 edges
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Starting Taint Analysis
[main] INFO soot.jimple.infoflow.android.data.AndroidMemoryManager - Initializing FlowDroid memory manager...
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Using context- and flow-sensitive solver
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Running with limited join point abstractions can break context-sensitive path builders
[main] INFO soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - Looking for sources and sinks...
[main] ERROR soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No sources found, aborting analysis
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
[main] WARN soot.jimple.infoflow.android.SetupApplication$InPlaceInfoflow - No results found.
Maximum memory consumption: 22.775696 MB
[main] INFO soot.jimple.infoflow.android.SetupApplication - Found 0 leaks
[main] INFO cova.setup.RunCova - Analyzing /media/malina/2312-47F7/Android apk/IF_covert_rec.apk
[main] INFO cova.source.parser.SourceParser - Read 15 APIs from /home/malina/Documents/Tools/COVA/cova/src/test/resources/config/Configuration_APIs.txt
[main] INFO cova.source.parser.UICallbackParser - Read 3 APIs from /home/malina/Documents/Tools/COVA/cova/src/test/resources/config/UICallback_APIs.txt
[main] INFO cova.core.RuleManager - 
CONFIG: UIConstraintCreationRule is enabled.
CONFIG: TaintConstraintCreationRule is enabled.
CONFIG: TaintPropagationRule is enabled.
CONFIG: SourceTaintCreationRule is enabled.
CONFIG: ImpreciseTaintCreationRule is enabled.
CONFIG: ImprecisePropagationRule is NOT enabled.
CONFIG: ConcreteTaintPropagationRule is enabled.
- ConcreteTaintAtAssignStmtOn is enabled
- ConcreteTaintAtReturnStmtOn is enabled
- ConcreteTaintAtCalleeOn is enabled
CONFIG: StaticFieldPropagationRule is NOT enabled.

[main] INFO cova.core.RuleManager - Mon Nov 25 14:47:05 HKT 2019
[main] INFO cova.core.ConstraintAnalysis - Analysis finished normally. Used analysis time: 0.003s
No leak was found by FlowDroid.Analysis is done!

**Comment by linghuiluo** [comment]
Good that it works now. For your app, you should check if the source and sink API are configured in this file https://github.com/secure-software-engineering/COVA/blob/master/cova/config/SourcesAndSinks.txt, because FlowDroid uses this file to find sources and sinks. You can add your source and sink to it.

**Comment by malinaaa** [comment]
Well, they are listed in the file you shared its link. Actually, the API source is of TelephonyManager and the sink is File classes. 
The main problem is that the Callgraph has 0 edges. How is it possible? Is it a problem with FlowDroid?

**Comment by linghuiluo** [comment]
if the callgraph has 0 edge, then it is the problem with FlowDroid. It can be that FlowDroid doesn't model the lifecycle. Since Android apps have no main entry point and FlowDroid creates a dummy main method which models the lifecycle. You can check if the callbacks in your android components are added to the dummy main method.

**Comment by geekySR** [comment]
@linghuiluo  Does it only work with java 8 and not with the higher versions?

**Comment by iamsaurabhr** [comment]
In my case, after executing the command, it says the analysis is done. But there is no such file called covaOutput where I can see the generated output.

![cova error](https://user-images.githubusercontent.com/40226779/183446089-abb812d7-2a4f-468e-a3bf-b474da6f299b.png)

**Comment by geekySR** [comment]
I tried to execute the command, But ended up with this error: 


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: 'soot.PatchingChain soot.Body.getUnits()'
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerPostBody(LibraryClassPatcher.java:384)
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchHandlerImplementation(LibraryClassPatcher.java:283)
        at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:44)
        at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1127)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1307)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1279)
        at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1244)
        at cova.setup.RunFlowDroid.run(RunFlowDroid.java:81)
        at cova.runner.AndroidApkAnalyzer.analyzeApk(AndroidApkAnalyzer.java:333)
        at cova.runner.AndroidApkAnalyzer.analyze(AndroidApkAnalyzer.java:262)
        at cova.runner.AndroidApkAnalyzer.main(AndroidApkAnalyzer.java:80)
        at cova.Main.main(Main.java:126)

**Comment by linghuiluo** [comment]
looks like you did not install soot, did you install the local libraries?  https://github.com/secure-software-engineering/COVA#21-build-the-tool-with-maven

**Comment by geekySR** [comment]
I tried to do that, but by mvn install never succeeds. Always end up with error.

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for de.upb.swt:cova_automatic:jar:0.0.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-surefire-plugin is missing. @ line 62, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for de.upb.swt:cova:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.soot-oss:soot:jar -> version 4.2.1 vs 4.3.0-SNAPSHOT @ line 205, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] cova-root                                                          [pom]
[INFO] apktool                                                            [jar]
[INFO] constraintBench                                                    [jar]
[INFO] cova                                                               [jar]
[INFO] cova_automatic                                                     [jar]
[INFO] covaIDE                                                            [jar]
[INFO]
[INFO] ------------------------< de.upb.swt:cova-root >------------------------
[INFO] Building cova-root 0.0.1-SNAPSHOT                                  [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ cova-root ---
[INFO] Installing C:\COVA\pom.xml to C:\Users\saura\.m2\repository\de\upb\swt\cova-root\0.0.1-SNAPSHOT\cova-root-0.0.1-SNAPSHOT.pom
[INFO]
[INFO] -------------------------< de.upb.swt:apktool >-------------------------
[INFO] Building apktool 0.0.1-SNAPSHOT                                    [2/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ apktool ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\COVA\apktool\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ apktool ---
[INFO] Changes detected - recompiling the module!
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] java\lang\System.java:[-1] No message
[ERROR] C:\COVA\apktool\src\main\java\brut\util\Jar.java:[67] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[728] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[961] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[994] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[998] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[20] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[21] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[37] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[38] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\decoder\AXmlResourceParser.java:[674] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\decoder\AXmlResourceParser.java:[752] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[156] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[164] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[169] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[174] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[179] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[190] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[195] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[196] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[872] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[935] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[995] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OS.java:[120] System cannot be resolved
[INFO] 24 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for cova-root 0.0.1-SNAPSHOT:
[INFO]
[INFO] cova-root .......................................... SUCCESS [  0.320 s]
[INFO] apktool ............................................ FAILURE [  2.353 s]
[INFO] constraintBench .................................... SKIPPED
[INFO] cova ............................................... SKIPPED
[INFO] cova_automatic ..................................... SKIPPED
[INFO] covaIDE ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.857 s
[INFO] Finished at: 2022-08-10T17:52:07+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project
 apktool: Compilation failure: Compilation failure:
[ERROR] java\lang\System.java:[-1] No message
[ERROR] C:\COVA\apktool\src\main\java\brut\util\Jar.java:[67] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[728] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[961] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[994] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\AndrolibResources.java:[998] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[20] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[21] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[37] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OSDetection.java:[38] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\decoder\AXmlResourceParser.java:[674] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\androlib\res\decoder\AXmlResourceParser.java:[752] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[156] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[164] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[169] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[174] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[179] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[190] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[195] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[196] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[872] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[935] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\org\xmlpull\renamed\MXSerializer.java:[995] System cannot be resolved
[ERROR] C:\COVA\apktool\src\main\java\brut\util\OS.java:[120] System cannot be resolved
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :apktool
